# Generated by Django 2.0.2 on 2020-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='copied',
            field=models.BooleanField(default=False),
        ),
    ]
