# Generated by Django 2.0.2 on 2020-07-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='creator',
        ),
    ]
