# Generated by Django 2.0.2 on 2020-09-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0003_auto_20200919_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='added',
            old_name='cardID',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='added',
            old_name='userID',
            new_name='user',
        ),
    ]
