# Generated by Django 2.0.2 on 2020-09-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0004_auto_20200919_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='added',
            name='card',
        ),
        migrations.RemoveField(
            model_name='added',
            name='user',
        ),
        migrations.RemoveField(
            model_name='card',
            name='added_total',
        ),
        migrations.DeleteModel(
            name='Added',
        ),
    ]
