# Generated by Django 2.0.2 on 2020-07-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0005_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(to='spaced_repitition.Deck'),
        ),
    ]
