# Generated by Django 2.0.2 on 2020-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0006_auto_20200923_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='leitner_box',
            field=models.IntegerField(default=1),
        ),
    ]
