# Generated by Django 2.0.2 on 2020-08-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0006_card_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='days_to_study',
            field=models.CharField(default=1, max_length=99999999),
            preserve_default=False,
        ),
    ]
