# Generated by Django 2.0.2 on 2020-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0007_card_days_to_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='days_to_study',
            field=models.IntegerField(default=0),
        ),
    ]
