# Generated by Django 2.0.2 on 2020-08-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0008_auto_20200815_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='days_to_study',
            field=models.IntegerField(default=1),
        ),
    ]
