# Generated by Django 2.0.2 on 2020-08-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0009_auto_20200815_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='days_to_study',
            new_name='days_till_study',
        ),
    ]
