# Generated by Django 2.0.2 on 2020-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repitition', '0011_deck_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
